#!/bin/bash

DOTFILES_PATH="${HOME}/dotfiles"
DIRCOLORS_PATH="${DOTFILES_PATH}/dircolors"
GITHUB_URL="https://github.com/ryomtmt/dotfiles.git"

cd ${HOME}

installed_groups=$(LANG=C yum grouplist | sed '/^Installed Groups:/,$!d;/^Available Groups:/,$d;/^Installed Groups:/d;s/^[[:space:]]*//')
if echo ${installed_groups}}|grep 'Development' > /dev/null; then
  sudo yum update
else
  sudo yum update
  sudo yum groupinstall -y "Development Tools"
fi

sudo yum install -y gcc zlib-devel bzip2 bzip2-devel readline readline-devel sqlite sqlite-devel openssl openssl-devel git libffi-devel
sudo yum install -y epel-release
sudo yum install -y jq

if [[ $(which git 2>/dev/null) ]] ; then
  if [[ -d ${DOTFILES_PATH} ]] ; then
    cd ${DOTFILES_PATH}
    git pull
  else
    git clone --recursive ${GITHUB_URL} ${DOTFILES_PATH}
  fi
else
  sudo yum install -y git
  if [[ -d ${DOTFILES_PATH} ]] ; then
    cd ${DOTFILES_PATH}
    git pull
  else
    git clone --recursive ${GITHUB_URL} ${DOTFILES_PATH}
  fi
fi

cd ${DOTFILES_PATH}
for dotfile in .?*
do
  if [ $dotfile != '..' ] && [ $dotfile != '.git' ]
  then
    ln -fs "$PWD/$dotfile" $HOME
  fi
done

if [[ -d ${DIRCOLORS_PATH} ]] ; then
  curl -o dircolors/dircolors.solarized-ansi-dark --create-dirs \
    -sSL https://raw.githubusercontent.com/seebi/dircolors-solarized/master/dircolors.ansi-dark
  curl -o dircolors/dircolors.molokai --create-dirs \
    -sSL https://raw.githubusercontent.com/gcollura/dotfiles/master/dircolors/dircolors.molokai
fi

mkdir -p ~/.vim/autoload ~/.vim/colors ~/.vim/plugged
curl -fsLo ~/.vim/autoload/plug.vim --create-dirs \
  https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
curl -fsLo ~/.vim/colors/molokai.vim --create-dirs \
  https://raw.githubusercontent.com/tomasr/molokai/master/colors/molokai.vim

vim +'PlugInstall --sync' +qa

if [[ -d ~/bin ]] ; then
  :
else
  mkdir -p ~/bin
fi

git clone https://github.com/pyenv/pyenv.git ~/.pyenv

exec $SHELL -l
